### ISSUE TITLE
Support multiple html-stuff directories

### ISSUE THREAD

**Issue by osv** [cheunghy/ac-html#14]
I think will be great if many customizable source directories will be available for user setup.
Different directory tree like for bootstrap or for example angular.js. So other project, let say ac-html-bootstrap, that populate "class" completion for div, button, etc and some new attributes, may be started separately. But need way to enable source of "html-stuff" locally for each buffer by user command setting variable like directly in html file:

```html
<!-- Local Variables:
 eval: (ac-html-bootstrap t)
 End
-->
```

**Comment by osv** [comment]
Hello!

Want to ask, when branch will be merged? Want to publish other modules that depend on ac-html.
You may give me access if busy nowadays :)

**Comment by cheunghy** [comment]
Hello!

Sorry for that. I am busy these days.
If you are adding new features, you can use your forked repo.

If it's something else, could you explain what it is and how it works?

Thanks

Zhang Kai Yu

**Comment by osv** [comment]
Well, I have 2 project, [ac-html-bootstrap](https://github.com/osv/ac-html-bootstrap) bootstrap class helper and [ac-html-csswatcher](https://github.com/osv/ac-html-csswatcher) (css, less class completion for project), both require multidir branch and pull https://github.com/cheunghy/ac-html/pull/22
That all. Want MELPAing both.

**Comment by osv** [comment]
Ah, also there  is https://github.com/osv/ac-html/compare/multy_dirs_tests branch that fix test using 2 sets of fixtures, I think better than broken test after merging multidir branch

**Comment by cheunghy** [comment]
Merged.

Thanks!

**Comment by osv** [comment]
Thanks!

**Comment by osv** [comment]
ah, olso maybe good idea to bump version, to make sure my module depend on fresh ac-html :)

**Comment by cheunghy** [comment]
Bumped version to 0.3

When the nice packages are available on melpa, notify me. I will update README.md to include them.

**Comment by osv** [comment]
Sure
