### ISSUE TITLE
Melpa: tar not found.Please Update

### ISSUE THREAD

**Issue by PetersonLian** [cheunghy/ac-html#26]
I tried to install ac-html using melpa source inside my emacs. I got the following error  

    url-insert-file-contents: http://melpa.milkbox.net/packages/ac-html-20150118.2116.tar: Not found

**Comment by cheunghy** [comment]
You can download this tar instead :D
http://melpa.org/packages/ac-html-20150430.1928.tar

**Comment by PetersonLian** [comment]
@cheunghy Thanks,that's what I did.  
But I still think it's better to update this package on melpa.  
At the end of the day, installing packages through 'package-list-packages is still an easier way for dummies like me. It can save sometime for us since we didn't need to google 'how to install tar package in emacs'

**Comment by osv** [comment]
My `list-packages` show Melpa's version `20150430.1928`, maybe you have try install  at moment  `ac-html` updating and old package removed, try again `list-packages`

**Comment by cheunghy** [comment]
Yeah, that's the idea. @osv is right!
I tried to download it from package-list-packages, and it installs fine. :D

**Comment by cheunghy** [comment]
Yeah, that's the idea. @osv is right!
I tried to download it from package-list-packages, and it installs fine. :D

**Comment by cheunghy** [comment]
Yeah, that's the idea. @osv is right!
I tried to download it from package-list-packages, and it installs fine. :D
