### ISSUE TITLE
Sharing web completion data

### ISSUE THREAD

**Issue by purcell** [cheunghy/ac-html#27]
@osv made a [Company version](https://github.com/osv/company-web) of `ac-html`, which initially depended on `ac-html` for its completion data. I suggested he extract the completion data into a separate package which you could both use, and he's done that in https://github.com/osv/web-completion-data.

Please would you consider changing `ac-html` so that it obtains its completion data from there instead? I'm sure @osv would be willing to add you as a committer to the `web-completion-data` repo if necessary.

Thanks!

**Comment by cheunghy** [comment]
Sure, I will do it within a week.

**Comment by osv** [comment]
Hello Cheunghy,

 I will prepare the patch by the end of the day, it almost ready :)

**Comment by purcell** [comment]
Great, thanks guys -- always nice to see Open Source collaboration at work! :-)

**Comment by cheunghy** [comment]
I've mreged pull request https://github.com/cheunghy/ac-html/pull/28 and update ac-html recipe https://github.com/milkypostman/melpa/pull/2745
Thanks you guys!
